### ISSUE TITLE
Set pick-up time for admin created order

### ISSUE THREAD

**Issue by NCS-Thomas** [WC-Local-Pickup/woocommerce-local-pickup-time#100]
For a customer I integrated this plugin.
The customer receives (secondarily) orders placed by phone.
The customer add the order via the WooCommerce > Orders > Add Order form.
On this form Pickup Time is reported as "none" since there isn't any yet.
The customer wants to set a Pickup Time for the order.

Is this just not possible, or am I missing something obvious.

**Comment by timnolte** [comment]
This is a duplicate if https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/9
