### ISSUE TITLE
Duplicate sentence on checkout page

### ISSUE THREAD

**Issue by smeric** [WC-Local-Pickup/woocommerce-local-pickup-time#104]
**Is your feature request related to a problem? Please describe.**
See here : /public/class-local-pickup-time.php#L687
And there : /public/class-local-pickup-time.php#L694
Maybe you should replace the second "Pickup Time" with something else, because as it is now you have twice the same sentence appearing one after the other on checkout page : "Pickup Time" as a title then as a field label.

**Describe the solution you'd like**
You may use "Please select a pickup time." as it exists already ? Or anything else...

**Describe alternatives you've considered**
Use CSS to hide the field label : `.local-pickup-time-select-field label {display:none;}`

**Additional context**

**Comment by smeric** [comment]
Here is another alternative. I add this snippet to my `function.php`. This removes the title entirely so I get rid of the duplicate sentence, resolving at the same time the `<h2>` probleme (see #103)  :
```php
/**
 * Remove the WooCommerce Local Pickup Time plugin checkout page select field title.
 *
 * @see https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/103
 * @see https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/104
 */
if ( class_exists( 'Local_Pickup_Time' ) ) {
    // Remove the default local pickup time field from the checkout page.
    remove_action( apply_filters( 'local_pickup_time_select_location', 'woocommerce_after_order_notes' ), array( Local_Pickup_Time::get_instance(), 'time_select') );
    // And add this custom one.
    add_action( apply_filters( 'local_pickup_time_select_location', 'woocommerce_after_order_notes' ), 'my_custom_time_select' );

    /**
     * Add the local pickup time field to the checkout page
     *
     * @param object $checkout The checkout object.
     */
    function my_custom_time_select( $checkout ) {
        echo '<div id="local-pickup-time-select">';

        $lpt = Local_Pickup_Time::get_instance();
        woocommerce_form_field(
            'local_pickup_time_select',
            array(
                'type'     => 'select',
                'class'    => array( 'local-pickup-time-select-field form-row-wide' ),
                'label'    => __( 'Pickup Time', 'woocommerce-local-pickup-time' ),
                'required' => true,
                'options'  => $lpt->build_pickup_time_options(),
            ),
            $checkout->get_value( 'local_pickup_time_select' )
        );

        echo '</div>';
    }
}
```

**Comment by VinGrade** [comment]
The function build_pickup_time_options doesn't exit anymore, use get_pickup_time_options instead.

**Comment by smeric** [comment]
@VinGrade yes, I learned that the hard way because of all the 500 errors I had to correct after the upgrade... Maybe keeping this function as deprecated would have saved me and my readers some hours... I beleave it's a bad habbit to rename public functions like that without providing retrocompatibility... anyway, thanks for your comment :)
