### ISSUE TITLE
Pickup time not showing after updating the WordPress 5.6

### ISSUE THREAD

**Issue by plantforsoul** [WC-Local-Pickup/woocommerce-local-pickup-time#108]
I loved the plugin and it worked without any issue since I installed it. Looks like after I updated the WordPress 5.6 it's not showing the pickup time dropdown anymore.. Could you please help?
Thanks

**General usage and development questions**
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce-local-pickup-time-select/

**Comment by timnolte** [comment]
@plantforsoul sorry for the long delay. I'm wondering if you have something else that is conflicting with this plugin. I have an up-to-date [WordPress 5.6 test install](https://testing.wclocalpickup.com/) and the plugin is showing the dropdown just fine. Can you provide the following details:

- Website URL: 
- PHP Version: 
- WordPress Version: 
- WooCommerce Version: 
- Local Pickup Time Plugin Version: 
- WordPress Timezone Setting: 
- WordPress Date Format Setting: 
- WordPress Time Format Setting: 
- All Plugin Start/End Pickup Time Settings: 
- Plugin Pickup Time Interval Setting: 
- Plugin Pickup Time Delay Setting: 
- Plugin Pickup Time Open Days Ahead Setting: 
- Other WooCommerce Addons/Plugins Installed:

**Comment by plantforsoul** [comment]
Hi Tim,
Thank you so much for reaching out. I really appreciate that. Please find
the information below you requested:
Please let me know if you have any other questions.
Thanks

   - Website URL: plantforsoul.ca
   - PHP Version: 7.2.34
   - WordPress Version: 5.6
   - WooCommerce Version: 4.8.0
   - Local Pickup Time Plugin Version: Version 1.3.12
   - WordPress Timezone Setting:UTC-5
   - WordPress Date Format Setting: January 9, 2021
   - WordPress Time Format Setting: 9:46 pmg:i a
   - All Plugin Start/End Pickup Time Settings: Store Hours and Closings
   for Local Pickup

   The following options affect when order pickups begin and end each day,
   and which days to not allow order pickups.
   Monday Pickup Start Time (use 24-hour time)
   Monday Pickup End Time (use 24-hour time)
   Tuesday Pickup Start Time (use 24-hour time)
   Tuesday Pickup End Time (use 24-hour time)
   Wednesday Pickup Start Time (use 24-hour time)
   Wednesday Pickup End Time (use 24-hour time)
   Thursday Pickup Start Time (use 24-hour time)
   Thursday Pickup End Time (use 24-hour time)
   Friday Pickup Start Time (use 24-hour time)
   Friday Pickup End Time (use 24-hour time)
   Saturday Pickup Start Time (use 24-hour time)
   Saturday Pickup End Time (use 24-hour time)
   Sunday Pickup Start Time (use 24-hour time)
   Sunday Pickup End Time (use 24-hour time)
   Store Closing Days (use MM/DD/YYYY format)
   Pickup Time Interval   5 minutes  10 minutes  15 minutes  20 minutes  30
   minutes  45 minutes  1 hour  2 hours  2 hours
   Pickup Time Delay   5 minutes  10 minutes  15 minutes  20 minutes  30
   minutes  45 minutes  1 hour  2 hours  4 hours  8 hours  16 hours  24
   hours  36 hours  48 hours  3 days  5 days  1 week  1 hour
   Pickup Time Open Days Ahead
   - Plugin Pickup Time Interval Setting: As above
   - Plugin Pickup Time Delay Setting: as above
   - Plugin Pickup Time Open Days Ahead Setting: as above
   - Other WooCommerce Addons/Plugins Installed:
   Active plugins (48)
   Woocommerce QuickBooks Connector <http://www.techspawn.com/>   by
   Techspawn Solutions – 2.1.3
   Advanced Local Pickup for WooCommerce <https://www.zorem.com/shop>   by
   zorem – 1.2.5
   Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro
   <https://codewoogeek.online/shop/free-plugins/back-in-stock-notifier/>   by
   codewoogeek – 1.10.0
   CartFlows <https://cartflows.com/>   by CartFlows Inc – 1.6.1
   Chat Session Addon <https://www.quantumcloud.com/products/plugins/>   by
   Quantumcloud – 2.2.3
   Chatbot Extended UI Addon
   <https://www.quantumcloud.com/products/plugins/>   by QuantumCloud –
   1.0.0
   Chatbot Settings Export Import
   <https://wordpress.org/plugins/woowbot-woocommerce-chatbot/>   by
   QunatumCloud – 1.0.0
   Contact Form 7 <https://contactform7.com/>   by Takayuki Miyoshi – 5.3.2
   Add-on: Unsubscribe - Back In Stock Notifier for WooCommerce
   <https://codewoogeek.online/shop/back-in-stock-notifier/unsubscribe/>   by
   codewoogeek – 1.2
   Disable Blogging <https://wordpress.org/plugins/disable-blogging/>   by
   Fact Maven – 2.1.0
   Elementor
   <https://elementor.com/?utm_source=wp-plugins&utm_campaign=plugin-uri&utm_medium=wp-dash>
     by Elementor.com – 3.0.16
   WooCommerce FedEx Shipping Plugin with Print Label
   <https://www.pluginhive.com/product/woocommerce-fedex-shipping-plugin-with-print-label/>
     by PluginHive – 4.7.1
   G5Plus Post Like <http://g5plus.net/>   by g5plus – 1.1
   WPZOOM Instagram Widget
   <https://www.wpzoom.com/plugins/instagram-widget/>   by WPZOOM – 1.7.3
   Jetpack by WordPress.com <https://jetpack.com/>   by Automattic – 9.2.1
   WPBakery Page Builder <http://wpbakery.com/>   by Michael M -
   WPBakery.com – 6.2.0
   Judge.me Product Reviews for WooCommerce <https://judge.me/>   by
   Judge.me – 1.3.8
   LiveChat Addon <https://www.quantumcloud.com/products/plugins/>   by
   QuantumCloud – 2.0.1
   Lustria Framework <http://g5plus.net/>   by g5plus – 1.7
   Mailchimp for WooCommerce <https://mailchimp.com/connect-your-store/>   by
   Mailchimp – 2.5.0
   MC4WP: Mailchimp for WordPress
   <https://www.mc4wp.com/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=plugins-page>
     by ibericode – 4.8.1
   Messenger ChatBot Addon <https://www.quantumcloud.com/products/plugins/>
     by QuantumCloud – 2.0.4
   My WP Backup Pro <https://mythemeshop.com/plugins/my-wp-backup-pro/>   by
   MyThemeShop – 1.3.8
   PageLayer <http://wordpress.org/plugins/pagelayer/>   by Pagelayer Team
   – 1.4.3
   WooCommerce react pos addon   by Webkul – 1.0.0
   Post Views Counter <http://www.dfactory.eu/plugins/post-views-counter/>   by
   Digital Factory – 1.3.3
   PW WooCommerce Gift Cards Pro <https://www.pimwick.com/gift-cards/>   by
   Pimwick, LLC – 1.292
   Slider Revolution <https://revolution.themepunch.com/>   by ThemePunch –
   6.2.9
   Stop WP Emails Going to Spam
   <http://fullworks.net/wordpress-plugins/stop-wp-emails-going-to-spam/>   by
   Fullworks – 1.1.4
   WooCommerce Cart Abandonment Recovery <https://cartflows.com/>   by
   CartFlows Inc – 1.2.8
   WooCommerce Point of Sale
   <https://store.webkul.com/woocommerce-point-of-sale.html>   by Webkul –
   3.5.0
   QR & Barcode Generator Label Printing Premium - Woolabel
   <https://woolabel.com/>   by Wooaddons – 1.2.1
   WooCommerce Advanced Free Shipping
   <https://wordpress.org/plugins/woocommerce-advanced-free-shipping/>   by
   Jeroen Sormani – 1.1.4
   WooCommerce Canada Post Webservice Method
   <https://truemedia.ca/plugins/cpwebservice/>   by Jamez Picard – 1.6.12
   WooCommerce Stripe Gateway
   <https://wordpress.org/plugins/woocommerce-gateway-stripe/>   by
   WooCommerce – 4.7.0
   WooCommerce Max Quantity
   <https://isabelcastillo.com/free-plugins/woocommerce-max-quantity>   by
   Isabel Castillo – 1.5.2
   WooCommerce PDF Invoices & Packing Slips <http://www.wpovernight.com/>   by
   Ewout Fernhout – 2.7.3
   WooCommerce Pre-Orders
   <https://woocommerce.com/products/woocommerce-pre-orders/>   by
   WooCommerce – 1.5.27
   WooCommerce Purolator Webservice Method
   <https://truemedia.ca/plugins/purowebservice/>   by Jamez Picard – 1.3.9
   WooCommerce Shipping & Tax <https://woocommerce.com/>   by Automattic –
   1.25.4
   WooCommerce Store Credit <https://woocommerce.com/products/store-credit/>
     by Themesquad – 3.4.4
   WooCommerce <https://woocommerce.com/>   by Automattic – 4.8.0
   WoowBot Pro Max <https://wordpress.org/plugins/wpbot-wordpress-chatbot/>
     by QuantumCloud – 13.0.7
   WP Mail SMTP <https://wpmailsmtp.com/>   by WPForms – 2.5.1
   WPS Hide Login   by WPServeur, NicolasKulka, wpformation – 1.6.1
   YITH WooCommerce Barcodes Premium
   <https://yithemes.com/themes/plugins/yith-woocommerce-barcodes-and-qr-codes/>
     by YITH – 2.0.0
   YITH WooCommerce Compare
   <https://yithemes.com/themes/plugins/yith-woocommerce-compare/>   by
   YITH – 2.4.3
   YITH WooCommerce Wishlist
   <https://yithemes.com/themes/plugins/yith-woocommerce-wishlist/>   by
   YITH – 3.0.17
   Inactive plugins (19)
   Bargaining Chatbot <https://www.quantumcloud.com/products/plugins/>   by
   QunatumCloud – 1.5.9
   Chatbot STR Pro Addon <https://www.quantumcloud.com/>   by QuantumCloud
   – 1.0.2
   Conversational Form Builder Pro <https://www.quantumcloud.com/>   by
   QuantumCloud – 1.4.8
   Envato Market <https://envato.com/market-plugin/>   by Envato – 2.0.6
   Extended Search Addon <https://www.quantumcloud.com/products/plugins/>   by
   QuantumCloud – 1.5.6
   Facebook for WooCommerce
   <https://github.com/facebookincubator/facebook-for-woocommerce/>   by
   Facebook – 2.2.0
   Google Ads & Marketing by Kliken <https://woo.kliken.com/>   by Kliken –
   1.0.6
   Loginizer <https://wordpress.org/extend/plugins/loginizer/>   by
   Softaculous – 1.6.5
   Mailing List Integration AddOn
   <https://www.quantumcloud.com/products/chatbot-addons/>   by
   QunatumCloud – 1.1.2
   Profitori <https://profitori.com/>   by Unity Business Technology Pty
   Ltd – 1.6.6.1
   Voice Message for WPBot <https://quantumcloud.com/>   by QuantumCloud –
   1.0.2
   White Label ChatBot Addon
   <https://www.quantumcloud.com/products/plugins/>   by QunatumCloud –
   1.2.3
   WooCommerce Checkout Add-Ons
   <http://www.woocommerce.com/products/woocommerce-checkout-add-ons/>   by
   SkyVerge – 2.5.0
   WooCommerce Google Analytics Integration
   <https://wordpress.org/plugins/woocommerce-google-analytics-integration/>
     by WooCommerce – 1.5.0
   WooCommerce Local Pickup Time Select <http://mattbanks.me/>   by Matt
   Banks – 1.3.12
   WooCommerce Product Bundles
   <https://woocommerce.com/products/product-bundles/>   by SomewhereWarm –
   6.6.4
   WooCommerce Product Vendors
   <https://woocommerce.com/products/product-vendors/>   by WooCommerce –
   2.1.45
   Woo Manage Fraud Orders
   <https://prasidhda.com.np/how-to-blacklist-customers-from-placing-order-in-woocommerce/>
     by Prasidhda Malla – 1.6.2
   WPBot Multi-Language Addon
   <https://wordpress.org/plugins/wpbot-wordpress-chatbot/>   by
   QuantumCloud – 1.0.0

**Comment by timnolte** [comment]
The plugins has just been updated and tested with the latest version of WordPress. This shouldn't be an issue any longer.
