### ISSUE TITLE
Select Pickup Time Required Even When Shipping is Selected

### ISSUE THREAD

**Issue by rebuys** [WC-Local-Pickup/woocommerce-local-pickup-time#116]
When a product that has local pickup and UPS as a shipping method "Select Pickup Time" is required even when UPS is selected.  
Customers who are not local and expect their product to be delivered to a different State, have to choose a pick up time.

1. I have two shipping methods, the first method is Local Pickup/Delivery/Shipping. It allows Free Local Pickup, Local Delivery, UPS and USPS.  The second method is Local Only No Shipping which allows Local Only.
2. When a product is added with the Local Pickup/Delivery/Shipping method the customer is forced to choose a pickup time even though they select UPS as a shipping method. 

**Expected behavior**
When a shipping method includes local pickup and shipping options and the customer chooses Shipping (UPS), the pickup time selector goes away and is not shown or required.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and this plugin are active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- Website URL:  https://rebuys.net
- PHP Version:  7.4.14
- WordPress Version:  5.6..1
- WooCommerce Version:  4.9.2
- Plugin Version: 1.3.12
- WordPress Timezone Setting:  CDT
- WordPress Date Format Setting:  
- WordPress Time Format Setting: 
- All Plugin Start/End Pickup Time Settings: 
- Plugin Pickup Time Interval Setting: 
- Plugin Pickup Time Delay Setting: 
- Plugin Orders Per Interval: 
- Plugin Pickup Time Open Days Ahead Setting:

**Comment by timnolte** [comment]
@rebuys FYI, yes, this is a known issue and it being tracked on Issue https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/23

Hoping to have this available in the next feature release.
