### ISSUE TITLE
How do i disable local pickup time for preorder products only while retaining for non preorder products?

### ISSUE THREAD

**Issue by HappyIrish** [WC-Local-Pickup/woocommerce-local-pickup-time#125]
**General usage questions**
If your question hasn't been answered in the Wiki please check the [Discussions](https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/discussions) for possible solutions or post a new question there.

**Comment by timnolte** [comment]
This situation would get resolved if https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/60 was implemented.
