### ISSUE TITLE
Time select dropdown box issues

### ISSUE THREAD

**Issue by vickyr-lbh** [WC-Local-Pickup/woocommerce-local-pickup-time#126]
Hello
I've been using the plugin with great success, thank you. But after a recent website rebuild and reinstallation of the plugin, I'm experiencing an issue with the time select box.
I followed the very helpful information on hiding the box if any other form of shipping is chosen by a customer and that works perfectly.
However, if someone changes from a different delivery to pickup on the checkout page, the box doesn't show *unless* you refresh the page, when it loads up.  If you try and checkout it comes up with an error message that a pickup time is needed, but the box doesn't show.
I was trying to edit the error message so that it would tell customers to refresh the page to load the selector box but I can't find where to do this. Anyone any ideas?
Or is there a different way around this so that the box appears immediately if someone changes delivery option on the checkout page?
Many thanks

**Comment by timnolte** [comment]
This related to the open engagement request https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/23
