### ISSUE TITLE
Still have an issue - drop down box

### ISSUE THREAD

**Issue by vickyr-lbh** [WC-Local-Pickup/woocommerce-local-pickup-time#128]
Hello

My last post was closed without a reply, saying it related to a previous post (on which I had commented). I implemented the code in that thread and it fixed the issue I had, hiding the dropdown box when any other form of shipping was selected.

That still works.

The problem I have is that if someone changes the shipping method on the checkout page from delivery to pickup, the dropdown doesn't appear *unless* the browser refresh button is hit. If you try and checkout without hitting the refresh button to get the dropdown box to appear, you can't because the error message appears saying please choose a collection time, which you can't do as the box isn't there.

If I can't resolve this issue, I would like to be able to change that error message to tell customers to hit the refresh button to get the dropdown to appear but I can't find how to do this.  And that was what I was asking for help with, please.

Thank you.

**Comment by timnolte** [comment]
@vickyr-lbh I had indicated(https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/126#issuecomment-808600965) that your post was already being tracked on an existing feature enhancement. You can follow the issues I mentioned in that comment for further updates. The code that you are using to hide when the dropdown is shown is not provided, or supported, by me. An officially supported solution is being planned for the next feature release, once I can devote the time to getting ti completed. Thos that have already attempted to provide a temporary fix may be able to to provide additional support if you keep your questions within that original issue(https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/23). Thanks!
