### ISSUE TITLE
Limit orders to a specific number at the same pickup time

### ISSUE THREAD

**Issue by mike-battistella** [WC-Local-Pickup/woocommerce-local-pickup-time#131]
**Is your feature request related to a problem? Please describe.**
In small restaurants or stores it's not possible to serve multiple customers picking up an order at the same time. The number of possible pickups differs from store to store.

**Describe the solution you'd like**
A possibility (a number) to set the maximum number of pickups a the same time — from 1 to 10 (some bigger number). E.g. if 1 is set only 1 customer can select a pickup date time of 17/May/2021@10:00 o'clock. For other customers this timeslot is not shown in the selection dropdown.

**Describe alternatives you've considered**
There is no alternative. Only hope that no twice or more customers select the same time slot ;)

**Additional context**
None

**Comment by timnolte** [comment]
@mike-battistella this request is already being tracked on issue https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/68

In order to provide this sort of feature a significant restructuring of how the plugin stores data is required in order not to negatively impact the performance of site checkout.

**Comment by mike-battistella** [comment]
> @mike-battistella this request is already being tracked on issue #68
> 
> In order to provide this sort of feature a significant restructuring of how the plugin stores data is required in order not to negatively impact the performance of site checkout.

Ok, thanks. Didn't manage to find the existing improvement request.

I've assumed that it will require some data management changes in the background.
