### ISSUE TITLE
Add Day

### ISSUE THREAD

**Issue by saltan88** [WC-Local-Pickup/woocommerce-local-pickup-time#132]
**General usage questions**

Hi, how to add day to the pickup selections 
at the moment it shows 14/9/21 @ 6.30pm 
can we show Tue, 14/9/21 6.30pm 

thank you

**Comment by timnolte** [comment]
@saltan88 the date/Tim format is currently driven by your site Date & Time formats. I have been asked about an enhancement to add a plugin specific date/time format but that hasn't been implemented yet.
