### ISSUE TITLE
Multiple pickup time slots

### ISSUE THREAD

**Issue by saltan88** [WC-Local-Pickup/woocommerce-local-pickup-time#133]
Hi just wondering how to have several time slots for example 11.30-3pm and 5-9pm ]
thank you 
**General usage questions**
If your question hasn't been answered in the Wiki please check the [Discussions](https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/discussions) for possible solutions or post a new question there.

**Comment by timnolte** [comment]
Closing as a duplicate of #110
