### ISSUE TITLE
Make pickup field selection bigger and with background

### ISSUE THREAD

**Issue by set088** [WC-Local-Pickup/woocommerce-local-pickup-time#135]
Hi,

Just wondering how to add a background colour and make the pickup selector bigger to make it more prominent/visible on the checkout page? Because some of our customers order without selecting a pickup time and said they’ve missed it.

thank you

**General usage questions**
If your question hasn't been answered in the Wiki please check the [Discussions](https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/discussions) for possible solutions or post a new question there.

**Comment by timnolte** [comment]
@set088 the Pickup Time will have some formatting changes, as well as location changes, in the upcoming 1.4.0 release. One key item in particular is that you will be able to link the Pickup Time selection directly to Local Pickup Shipping Methods within Shipping Zones. If you would like to change the styling of the Pickup Time output you can target this with CSS using the `id` that is on the surrounding `DIV` of the Pickup Time select field, which is `local_pickup_time_select`.
