### ISSUE TITLE
Pickup time is not shown in emails that are sent when a note is added to an order

### ISSUE THREAD

**Issue by bendison** [WC-Local-Pickup/woocommerce-local-pickup-time#88]
**Describe the bug**
When a customer note is added to an order, the email that is sent should contain the pickup time that was selected. The email currently displays the pickup time as "None".

**To Reproduce**
1. Create a new order for local pickup.
2. Check the email that is sent to the customer, it should contain a pickup time.
3. Add a customer order note which triggers an email being sent to the customer.
4. Check the new email that contains the note, the text for "Pickup Time:" should be "None".

**Screenshots**
First email, containing pickup time:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/11245752/84415842-604ef500-abe1-11ea-96a7-aba36a6cb2c3.png">

Second email sent with note, no pickup time:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/11245752/84415925-7c529680-abe1-11ea-8278-cdbf7b6266a7.png">

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce and this plugin are active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
- PHP Version: 7.3
- WordPress Version: 5.4.2
- WooCommerce Version: 4.2.0
- Plugin Version: 1.3.12

**Comment by dennisgon** [comment]
can I work on this issue?

**Comment by timnolte** [comment]
@dennisgon yes, for sure you are welcome to fork and submit a PR for this.

**Comment by dennisgon** [comment]
Hi I think this is because of other plugins
I already try  for myself and there is no problem
![image](https://user-images.githubusercontent.com/6257311/95018559-caa50d00-068a-11eb-9446-27110ad4924a.png)

**Comment by timnolte** [comment]
@bendison can you confirm if you have any additional plugins that modify the WooCommerce emails?

**Comment by timnolte** [comment]
@dennisgon thanks for your verification and analysis on this!

**Comment by timnolte** [comment]
Closing this as in my own recent testing customer notes as well as all other order emails appear to have the pickup time as expected.
