### ISSUE TITLE
Pickup Date/Time is showing as ARRAY in Order page (WordPress) and Emails

### ISSUE THREAD

**Issue by thebrownlows** [WC-Local-Pickup/woocommerce-local-pickup-time#89]
The selected pickup date/time is showing as the word ARRAY in email confirmations and within the orders page of WooCommerce in Wordpress itself. Therefore I have no visibility of the date/time selected by the user.

**Comment by timnolte** [comment]
I'm going to need more details. How did you create this issue? There should have been a template for you to fill out details.

**Comment by thebrownlows** [comment]
i'm not sure i understand, how did I create this issue.

Plugin is installed
Days available are Friday, Saturday, Sunday only.
Times allowed are Friday (4-6pm), Saturday and Sunday (10am-12noon)
28 days in advance
3 days before a date
latest version of wordpress (4.8.1 i think?)
Date picker seems to work ok.....but comes through as array on the email confirmation and within the order page (so no date/time) despite a date/time being selected when the order was placed.

**Comment by thebrownlows** [comment]
https://gatherforsupper.co.uk/ is the site it's associated with

**Comment by timnolte** [comment]
Hmm, when you open up an issue you should have been prompted with the type of issue you were opening with a template to fill out all the required details in order to troubleshoot your issue.

Please confirm your WordPress version, 4.8.x is old and no longer a supported version of WordPress. Please also confirm your WooCommerce version, PHP version, your WordPress General settings Date Format and Time Format. Thanks!

**Comment by timnolte** [comment]
@thebrownlows I just realized that you were the last person to comment on issue #23 indicating that you modified the plugin. If that is the case then I ask you to please reinstall the plugin to ensure that your code changes didn't cause this problem as well. Thanks.

**Comment by timnolte** [comment]
It is possible that I haven't pushed all of the changes to the remote yet, as I still have work on my local machine. I'm still sorting out GrumPHP and the build tools setup so that everything is ensured to be included in the repository and requiring minimal globally installed packages.

**Comment by thebrownlows** [comment]
??

**Comment by timnolte** [comment]
@thebrownlows what version of WooCommerce are you using?

**Comment by thebrownlows** [comment]
4.2.2

**Comment by timnolte** [comment]
@thebrownlows so I just setup a clean install with only WooCommerce & the Pickup Plugin installed and used your settings and I have no problem with seeing the pickup time in the order details view or the orders listing. If you can confirm what other WooCommerce plugins you have installed? There may be some conflict with another plugin. The other possibility is that you maybe need to install a fresh copy of the Pickup Plugin in case there still remains some modifications to the plugin. I'd also make sure that you don't have any other code somewhere else, like JavaScript you are loading into the frontend, that is attempting to modify how it works.

**Comment by timnolte** [comment]
Closing this as there is no support when customizing the plugin and there is a new release that fully supports custom statuses and email templates.
