### ISSUE TITLE
Transfer Plugin Ownership

### ISSUE THREAD

**Issue by mattbanks** [WC-Local-Pickup/woocommerce-local-pickup-time#95]
Hey @timnolte - I was thinking about transferring plugin ownership over to you, if you're interested. I haven't been involved in the active development here for a while (and probably won't be for the foreseeable future due to other commitments). Let me know if you want to do that! I can transfer the plugin ownership on WordPress.org ([info here](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/#plugin-ownership)) and we can move this repo if you'd like - whatever you want to do!

Let me know if you're interested :)

**Comment by timnolte** [comment]
@mattbanks I'd be happy to take over ownership. You can feel free to transfer the GitHub repo ownership to the organization I created(https://github.com/WC-Local-Pickup). You can go ahead and transfer the ownership on WordPress.org as well.

**Comment by mattbanks** [comment]
Transferred! Thanks for doing such a great job with the plugin!

**Comment by timnolte** [comment]
Thanks for all your previous work and getting this plugin going. I'm happy to be carrying things on.
