### ISSUE TITLE
checkout page time slot re-arrange needed

### ISSUE THREAD

**Issue by xianchuzhu** [WC-Local-Pickup/woocommerce-local-pickup-time#96]
sometime customer stay at check out page for like 30 mins or a hour before submitting the order.  by that time , current time already passed first available time slot. I am not sure if i made this clearly.
eg.   customer at check out page @ 2:25 .dealy was set 15mins. so first available time slot will be 2:45pm. but customer submited the order at 4pm and the pick time was still set at 2:45.

is there anyway to make them re selected for new time slot or make a page expire countdown to let them finish check out in 5 mins.

**Comment by timnolte** [comment]
This is already in an existing request: https://github.com/WC-Local-Pickup/woocommerce-local-pickup-time/issues/46
